const splash=document.querySelector('#splash'),logoIntro=document.querySelector('#logoIntro'),heroVideo=document.querySelector('#heroVideo'),skip=document.querySelector('#skipIntro'),sound=document.querySelector('#soundToggle'),confettiToggle=document.querySelector('#confettiToggle'),backgroundMusic=document.querySelector('#backgroundMusic');
const uiStyle=document.createElement('style');uiStyle.textContent=`body.splash-active #soundToggle,body.splash-active #confettiToggle{visibility:hidden!important;opacity:0!important;pointer-events:none!important}.confetti-toggle{position:absolute;z-index:12;right:28px;bottom:76px;border:1px solid #e5c77a66;background:#100e0c99;color:#f5ead7;padding:.65rem .9rem;cursor:pointer}.confetti-zone{position:relative;overflow:hidden}.confetti-zone>*:not(.confetti-layer){position:relative;z-index:2}.hero>video{z-index:0!important}.confetti-layer{position:absolute!important;inset:0!important;z-index:1!important;overflow:hidden!important;pointer-events:none!important;display:block}.hero .confetti-layer{z-index:8!important}.hero .sound,.hero .confetti-toggle,.hero .scroll{z-index:12!important}.confetti-piece{position:absolute!important;left:var(--x)!important;top:-35px!important;width:var(--w)!important;height:var(--h)!important;border-radius:var(--r)!important;background:var(--c)!important;opacity:var(--o)!important;box-shadow:0 0 var(--glow) var(--c);will-change:transform;animation:none!important}.confetti-piece.ribbon{border-radius:50% 12% 50% 12%!important}.confetti-piece.round{border-radius:50%!important}.confetti-piece.sliver{border-radius:40% 8% 40% 8%!important}.confetti-piece.spark{filter:brightness(1.16)}body.confetti-off .confetti-layer{display:none!important}@media(max-width:850px){.tools{display:flex!important;align-items:center!important;gap:.55rem!important}.langs{display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;gap:.3rem!important;font-size:.68rem!important;white-space:nowrap!important;position:relative!important;z-index:40!important}.langs a,.langs strong,.langs i{display:inline!important;visibility:visible!important;opacity:1!important}.hero .sound{right:14px!important;bottom:14px!important}.hero .confetti-toggle{display:block!important;visibility:visible!important;opacity:1!important;right:14px!important;bottom:58px!important;font-size:.7rem;padding:.5rem .7rem;transform:none!important}.confetti-piece{box-shadow:0 0 var(--glow) var(--c),0 0 calc(var(--glow) * 1.45) rgba(255,225,150,.14)}}`;document.head.appendChild(uiStyle);
let closed=false,musicOn=false,confettiOn=true;
function setMusicUI(on){musicOn=on;sound.textContent=on?'Звук: вкл.':'Звук: выкл.';sound.setAttribute('aria-label',on?'Выключить звук':'Включить звук')}
async function startBackgroundMusic(){try{backgroundMusic.muted=false;backgroundMusic.volume=.72;await backgroundMusic.play();setMusicUI(true);return true}catch(e){musicOn=false;sound.textContent='Звук: вкл.';return false}}
function enterSite(){if(closed)return;closed=true;splash.classList.add('hide');document.body.classList.remove('splash-active');heroVideo.play().catch(()=>{});startBackgroundMusic();setTimeout(()=>splash.remove(),900)}
logoIntro.addEventListener('ended',enterSite);logoIntro.addEventListener('error',enterSite);skip.addEventListener('click',enterSite);setTimeout(enterSite,7000);
const menu=document.querySelector('#menu'),nav=document.querySelector('.top nav');menu.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
startBackgroundMusic();document.addEventListener('DOMContentLoaded',startBackgroundMusic,{once:true});window.addEventListener('load',startBackgroundMusic,{once:true});
function unlockMusic(e){if(e.target.closest&&e.target.closest('#soundToggle'))return;if(!musicOn)startBackgroundMusic()}['pointerdown','touchstart','click','keydown'].forEach(evt=>document.addEventListener(evt,unlockMusic,{once:true,capture:true,passive:evt!=='keydown'}));
sound.addEventListener('click',async()=>{if(!musicOn)await startBackgroundMusic();else{backgroundMusic.pause();setMusicUI(false)}});heroVideo.addEventListener('ended',()=>{heroVideo.currentTime=0;heroVideo.play().catch(()=>{})});
const form=document.querySelector('form');if(form)form.addEventListener('submit',e=>{e.preventDefault();alert('Форма пока демонстрационная. Подключим отправку заявок при публикации сайта.')});
const sections=[...document.querySelectorAll('.confetti-zone')];const palette=['#FFD34E','#F6B817','#E69A2E','#FFF0A6','#D9A441','#B8862F','#FF6B7D','#FF9FB0','#F36B9A','#E8D8FF','#AFCBFF','#FFFFFF','#2F80FF','#54B8FF','#19D98B','#39E75F','#7B61FF'];
function makeConfetti(section,index){section.querySelectorAll(':scope > .confetti-layer').forEach(el=>el.remove());const layer=document.createElement('div');layer.className='confetti-layer';layer.setAttribute('aria-hidden','true');const mobile=window.matchMedia('(max-width:850px)').matches;const count=mobile?44:54;for(let i=0;i<count;i++){const p=document.createElement('i');const side=i%2===0?'left':'right';const edge=1.5+Math.random()*(mobile?13.5:17.5);const x=side==='left'?edge:100-edge;const shape=Math.random();const ribbon=shape<.34,longRibbon=shape>=.34&&shape<.48,round=shape>=.48&&shape<.62,sliver=shape>=.62&&shape<.80,spark=Math.random()<.34,rot=Math.floor(Math.random()*360),duration=9000+Math.random()*7000,delay=-Math.random()*duration-index*120;let width,height;if(longRibbon){width=mobile?2+Math.random()*2.2:2.5+Math.random()*3.5;height=mobile?18+Math.random()*20:30+Math.random()*34}else if(ribbon){width=mobile?2.8+Math.random()*3:3.5+Math.random()*5;height=mobile?11+Math.random()*15:17+Math.random()*24}else if(sliver){width=mobile?2+Math.random()*2.2:2.5+Math.random()*3.5;height=mobile?8+Math.random()*11:12+Math.random()*18}else if(round){width=mobile?4+Math.random()*5:6+Math.random()*8;height=width}else{width=mobile?3.5+Math.random()*5:5+Math.random()*8;height=mobile?5+Math.random()*8:7+Math.random()*13}const glow=spark?(mobile?5+Math.random()*7:9+Math.random()*10):(mobile?1.5+Math.random()*3:2+Math.random()*4);p.className='confetti-piece'+(ribbon||longRibbon?' ribbon':'')+(round?' round':'')+(sliver?' sliver':'')+(spark?' spark':'');p.style.cssText=`--x:${x}%;--w:${width}px;--h:${height}px;--r:${round?'50%':Math.random()<.25?'45%':'2px'};--c:${palette[Math.floor(Math.random()*palette.length)]};--o:${.8+Math.random()*.2};--glow:${glow}px`;layer.appendChild(p);const fall=Math.max(section.clientHeight,window.innerHeight)+120,drift=(Math.random()-.5)*(mobile?18:70);p.animate([{transform:`translate3d(0,-50px,0) rotate(${rot}deg)`},{transform:`translate3d(${drift*.15}px,${fall*.25}px,0) rotate(${rot+180}deg)`},{transform:`translate3d(${drift*-.12}px,${fall*.5}px,0) rotate(${rot+360}deg)`},{transform:`translate3d(${drift*.12}px,${fall*.75}px,0) rotate(${rot+540}deg)`},{transform:`translate3d(${drift}px,${fall}px,0) rotate(${rot+720}deg)`}],{duration,delay,iterations:Infinity,easing:'linear'})}section.appendChild(layer)}
function rebuildConfetti(){sections.forEach(makeConfetti)}rebuildConfetti();function setConfetti(on){confettiOn=on;document.body.classList.toggle('confetti-off',!on);if(on)rebuildConfetti();confettiToggle.textContent=on?'Конфетти: вкл.':'Конфетти: выкл.';confettiToggle.setAttribute('aria-pressed',String(on));confettiToggle.setAttribute('aria-label',on?'Выключить эффект конфетти':'Включить эффект конфетти')}confettiToggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setConfetti(!confettiOn)});setConfetti(true);
