const splash=document.querySelector('#splash'),logoIntro=document.querySelector('#logoIntro'),heroVideo=document.querySelector('#heroVideo'),skip=document.querySelector('#skipIntro'),sound=document.querySelector('#soundToggle'),confettiToggle=document.querySelector('#confettiToggle'),backgroundMusic=document.querySelector('#backgroundMusic');
const uiStyle=document.createElement('style');uiStyle.textContent=`body.splash-active #soundToggle,body.splash-active #confettiToggle{visibility:hidden!important;opacity:0!important;pointer-events:none!important}.confetti-toggle{position:absolute;z-index:12;right:28px;bottom:76px;border:1px solid #e5c77a66;background:#100e0c99;color:#f5ead7;padding:.65rem .9rem;cursor:pointer}.confetti-layer{position:absolute;inset:0;z-index:5;overflow:hidden;pointer-events:none}.confetti-piece{position:absolute;left:var(--x);top:-25px;width:var(--w);height:var(--h);border-radius:var(--r);background:var(--c);opacity:var(--o);transform:rotate(var(--rot));animation:pcFall var(--dur) linear infinite;animation-delay:var(--delay)}.confetti-piece.ribbon{border-radius:50% 10% 50% 10%}@keyframes pcFall{0%{transform:translate3d(0,-30px,0) rotate(var(--rot));}100%{transform:translate3d(var(--drift),calc(100vh + 60px),0) rotate(720deg)}}body.confetti-off .confetti-layer{display:none!important}@media(max-width:560px){.hero .sound{right:14px!important;bottom:14px!important;z-index:12!important}.hero .confetti-toggle{display:block!important;visibility:visible;right:14px!important;bottom:58px!important;z-index:12!important;font-size:.7rem;padding:.5rem .7rem;transform:none!important}}`;document.head.appendChild(uiStyle);
let closed=false,musicOn=false,confettiOn=true;
function setMusicUI(on){musicOn=on;sound.textContent=on?'Звук: вкл.':'Звук: выкл.';sound.setAttribute('aria-label',on?'Выключить звук':'Включить звук')}
async function startBackgroundMusic(){try{backgroundMusic.volume=.72;await backgroundMusic.play();setMusicUI(true);return true}catch(e){musicOn=false;sound.textContent='Звук: вкл.';return false}}
function enterSite(){if(closed)return;closed=true;splash.classList.add('hide');document.body.classList.remove('splash-active');heroVideo.play().catch(()=>{});startBackgroundMusic();setTimeout(()=>splash.remove(),900)}
logoIntro.addEventListener('ended',enterSite);logoIntro.addEventListener('error',enterSite);skip.addEventListener('click',enterSite);setTimeout(enterSite,7000);
const menu=document.querySelector('#menu'),nav=document.querySelector('.top nav');menu.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
startBackgroundMusic();document.addEventListener('DOMContentLoaded',startBackgroundMusic,{once:true});window.addEventListener('load',startBackgroundMusic,{once:true});
function unlockMusic(e){if(e.target.closest&&e.target.closest('#soundToggle'))return;if(!musicOn)startBackgroundMusic()}['pointerdown','touchstart','click'].forEach(evt=>document.addEventListener(evt,unlockMusic,{once:true,capture:true,passive:true}));
sound.addEventListener('click',async()=>{if(!musicOn)await startBackgroundMusic();else{backgroundMusic.pause();setMusicUI(false)}});heroVideo.addEventListener('ended',()=>{heroVideo.currentTime=0;heroVideo.play().catch(()=>{})});
const form=document.querySelector('form');if(form)form.addEventListener('submit',e=>{e.preventDefault();alert('Форма пока демонстрационная. Подключим отправку заявок при публикации сайта.')});
const sections=[document.querySelector('.hero'),document.querySelector('#philosophy'),document.querySelector('#contact')].filter(Boolean),palette=['#FFD34E','#F6B817','#E69A2E','#FFF0A6','#FF6B7D','#FF9FB0','#F36B9A','#F28C52','#E8D8FF','#AFCBFF','#FFFFFF'];
function makeConfetti(section,index){const layer=document.createElement('div');layer.className='confetti-layer';layer.setAttribute('aria-hidden','true');const count=innerWidth<560?24:54;for(let i=0;i<count;i++){const p=document.createElement('i'),edge=1.5+Math.random()*17.5,x=i%2?100-edge:edge;p.className='confetti-piece'+(Math.random()<.27?' ribbon':'');p.style.cssText=`--x:${x}%;--w:${5+Math.random()*8}px;--h:${8+Math.random()*12}px;--r:${Math.random()<.3?'50%':'2px'};--c:${palette[Math.floor(Math.random()*palette.length)]};--o:${.78+Math.random()*.22};--rot:${Math.floor(Math.random()*360)}deg;--dur:${6+Math.random()*8}s;--delay:${-Math.random()*14-index*1.7}s;--drift:${(Math.random()-.5)*105}px`;layer.appendChild(p)}section.appendChild(layer)}sections.forEach(makeConfetti);
function setConfetti(on){confettiOn=on;document.body.classList.toggle('confetti-off',!on);confettiToggle.textContent=on?'Конфетти: вкл.':'Конфетти: выкл.';confettiToggle.setAttribute('aria-pressed',String(on))}confettiToggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setConfetti(!confettiOn)});setConfetti(true);
